# -*- coding: utf-8 -*-
"""Multi_Stock_Trading_Strategy_Analysis_Portfolio_Analysis.ipynb

Automatically generated by Colab.

## Multi Stock Trading Strategy Analysis and Portfolio Analysis

#### Installations
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ta.momentum import RSIIndicator
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""### Analyse stocks with SMA, EMA and RSI Stratergy"""

# 1. LOAD DATA
def load_data(ticker, period="2y", interval="1d"):
    df = yf.download(ticker, period=period, interval=interval)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [col[0] for col in df.columns]
    df.dropna(inplace=True)
    return df

# 2. ADD INDICATORS
def add_indicators(df, sma_window=20, ema_window=50, rsi_window=14):
    df["SMA"] = df["Close"].rolling(window=sma_window).mean()
    df["EMA"] = df["Close"].ewm(span=ema_window, adjust=False).mean()
    df["RSI"] = RSIIndicator(df["Close"], window=rsi_window).rsi()
    return df

# 3. TRADING ENVIRONMENT
class TradingEnvironment:
    def __init__(self, initial_capital=10000):
        self.cash = initial_capital
        self.shares = 0
        self.portfolio_values = []

    def buy(self, price):
        if self.cash > 0:
            self.shares = self.cash / price
            self.cash = 0

    def sell(self, price):
        if self.shares > 0:
            self.cash = self.shares * price
            self.shares = 0

    def step(self, signal, price):
        if signal == 1:
            self.buy(price)
        elif signal == -1:
            self.sell(price)

        total_value = self.cash + self.shares * price
        self.portfolio_values.append(total_value)

def run_strategy(df, signal_column):
    env = TradingEnvironment()
    for i in range(len(df)):
        env.step(df[signal_column].iloc[i], df["Close"].iloc[i])
    df["PortfolioValue"] = env.portfolio_values
    return df

# 4. STRATEGIES
def sma_strategy(df):
    df["Signal"] = np.where(df["Close"] > df["SMA"], 1, -1)
    df["Position"] = df["Signal"].diff()
    return df

def ema_strategy(df, fast=12, slow=26):
    df["EMA_fast"] = df["Close"].ewm(span=fast, adjust=False).mean()
    df["EMA_slow"] = df["Close"].ewm(span=slow, adjust=False).mean()
    df["Signal"] = np.where(df["EMA_fast"] > df["EMA_slow"], 1, -1)
    df["Position"] = df["Signal"].diff()
    return df

def rsi_strategy(df, low=30, high=70):
    df["Signal"] = np.where(df["RSI"] < low, 1,
                     np.where(df["RSI"] > high, -1, 0))
    df["Position"] = df["Signal"].diff()
    return df

# 5. MULTI-STOCK PLOTTING
def plot_portfolio_comparison(results_dict, strategy_name):
    plt.figure(figsize=(8, 4))
    for ticker, df in results_dict.items():
        plt.plot(df.index, df["PortfolioValue"], label=ticker)
    plt.title(f"Portfolio Value Comparison Across Stocks - {strategy_name}")
    plt.xlabel("Date")
    plt.ylabel("Portfolio Value ($)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def total_return(df):
    return (df["PortfolioValue"].iloc[-1] - df["PortfolioValue"].iloc[0]) / df["PortfolioValue"].iloc[0]

def annualized_return(df):
    total_days = len(df)
    total_ret = df["PortfolioValue"].iloc[-1] / df["PortfolioValue"].iloc[0]
    return (total_ret ** (365 / total_days) - 1)

def sharpe_ratio(df):
    returns = df["PortfolioValue"].pct_change().dropna()
    return (returns.mean() / returns.std()) * np.sqrt(252)


tickers = ["BMNR", "BE", "OKLO", "IREN", "SNDK"]

# SMA
sma_results = {}
for t in tickers:
    df = load_data(t)
    df = add_indicators(df)
    df_sma = sma_strategy(df.copy())
    df_sma = run_strategy(df_sma, "Signal")
    print(f"\n {t} SMA Performance ")
    print("Total Return:", total_return(df_sma))
    print("Annualized Return:", annualized_return(df_sma))
    print("Sharpe Ratio:", sharpe_ratio(df_sma))
    sma_results[t] = df_sma
plot_portfolio_comparison(sma_results, "SMA Strategy")

# EMA
ema_results = {}
for t in tickers:
    df = load_data(t)
    df = add_indicators(df)
    df_ema = ema_strategy(df.copy())
    df_ema = run_strategy(df_ema, "Signal")
    print(f"\n {t} EMA Performance ")
    print("Total Return:", total_return(df_ema))
    print("Annualized Return:", annualized_return(df_ema))
    print("Sharpe Ratio:", sharpe_ratio(df_ema))
    ema_results[t] = df_ema
plot_portfolio_comparison(ema_results, "EMA Strategy")

#  RSI
rsi_results = {}
for t in tickers:
    df = load_data(t)
    df = add_indicators(df)
    df_rsi = rsi_strategy(df.copy())
    df_rsi = run_strategy(df_rsi, "Signal")
    print(f"\n {t} RSI Performance ")
    print("Total Return:", total_return(df_rsi))
    print("Annualized Return:", annualized_return(df_rsi))
    print("Sharpe Ratio:", sharpe_ratio(df_rsi))
    rsi_results[t] = df_rsi
plot_portfolio_comparison(rsi_results, "RSI Strategy")

"""## Strategy Performance Summary

Below are the performance metrics (Total Return, Annualized Return, Sharpe Ratio) for each ticker under the RSI, EMA, and SMA strategies.  
Each strategy was tested with an initial investment of **$10,000**, and the portfolio value was tracked over the full 2‑year period.

### **RSI Strategy**
- **BMNR:** Total Return = 510%, Annualized = 47.6%, Sharpe = 1.19  
- **BE:** Total Return = 130%, Annualized = 0.83, Sharpe = 1.27  
- **OKLO:** Total Return = 58%, Annualized = 0.39, Sharpe = 1.16  
- **IREN:** Total Return = 9.5%, Annualized = 0.06, Sharpe = 0.30  
- **SNDK:** Total Return = 21.8%, Annualized = 0.33, Sharpe = 0.73  

### **EMA Strategy**
- **BMNR:** Total Return = –33%, Annualized = –0.58, Sharpe = 0.36  
- **BE:** Total Return = 528%, Annualized = 2.80, Sharpe = 1.48  
- **OKLO:** Total Return = 1067%, Annualized = 4.96, Sharpe = 1.70  
- **IREN:** Total Return = 273%, Annualized = 1.60, Sharpe = 1.18  
- **SNDK:** Total Return = 1220%, Annualized = 44.3, Sharpe = 3.26  

### **SMA Strategy**
- **BMNR:** Total Return = –78%, Annualized = –0.96, Sharpe = –1.85  
- **BE:** Total Return = 626%, Annualized = 3.22, Sharpe = 1.59  
- **OKLO:** Total Return = 516%, Annualized = 2.75, Sharpe = 1.41  
- **IREN:** Total Return = 357%, Annualized = 2.01, Sharpe = 1.36  
- **SNDK:** Total Return = 1182%, Annualized = 42.4, Sharpe = 3.54

### Analysis

Across all tickers, the **EMA and SMA strategies clearly outperform RSI**, especially for high‑momentum stocks like OKLO and SNDK, which show extremely high total and annualized returns. RSI is inconsistent excellent for BMNR but weak for most other tickers indicating it depends heavily on mean‑reversion behavior. EMA performs best overall because it reacts faster to trend changes, while SMA is slightly slower but still strong for trending stocks. BMNR is the only ticker where both EMA and SMA struggle, showing that strategy effectiveness is highly stock‑dependent.

**Overall, EMA is the strongest and most consistent strategy, SMA performs well on trending stocks, RSI is unstable across tickers, and BMNR is the only stock where all strategies struggle.**

### Analyse stocks with ARIMA MODEL
"""

# 1. ARIMA MODEL
def run_arima(df, order=(5,1,0)):
    series = df["Close"]
    model = ARIMA(series, order=order)
    model_fit = model.fit()
    preds = model_fit.predict(start=1, end=len(series), dynamic=False)
    df["ARIMA_Pred"] = preds
    return df

# 2. ARIMA STRATEGY
def arima_strategy(df):
    df["Signal"] = np.where(df["ARIMA_Pred"] > df["Close"], 1, -1)
    df["Position"] = df["Signal"].diff()
    return df

# 3. RUN ARIMA FOR ALL STOCKS
arima_results = {}

for t in tickers:
    df = load_data(t)
    df = add_indicators(df)

    df_reset = df.copy().reset_index(drop=True)
    df_arima = run_arima(df_reset.copy())

    df_arima.index = df.index  # restore dates

    df_arima = arima_strategy(df_arima)
    df_arima = run_strategy(df_arima, "Signal")
    print(f"\n {t} ARIMA Performance ")
    print("Total Return:", total_return(df_arima))
    print("Annualized Return:", annualized_return(df_arima))
    print("Sharpe Ratio:", sharpe_ratio(df_arima))

    arima_results[t] = df_arima

plot_portfolio_comparison(arima_results, "ARIMA Strategy")

"""## ARIMA Strategy Performance Summary

We applied the ARIMA(5,1,0) forecasting model to each ticker with an initial investment of **$10,000**.  
Below are the performance metrics (Total Return, Annualized Return, Sharpe Ratio):

### **ARIMA Strategy**
- **BMNR:** Total Return = 118%, Annualized = 4.37, Sharpe = 1.05  
- **BE:** Total Return = 221%, Annualized = 1.33, Sharpe = 1.12  
- **OKLO:** Total Return = 220%, Annualized = 1.33, Sharpe = 1.14  
- **IREN:** Total Return = 152%, Annualized = 0.96, Sharpe = 0.96  
- **SNDK:** Total Return = 291%, Annualized = 6.52, Sharpe = 2.41  

### Analysis

The ARIMA strategy produced steady, moderate growth across all tickers, with SNDK showing the strongest performance both in total return and risk‑adjusted Sharpe Ratio. BMNR, BE, and OKLO delivered consistent gains, indicating that ARIMA captured their underlying price patterns reasonably well. IREN showed the weakest Sharpe Ratio, suggesting higher volatility relative to returns. Overall, ARIMA behaves as a stable but conservative forecasting‑based strategy compared to the more aggressive technical models.

**ARIMA provides stable, forecast-driven returns across all stocks, with SNDK emerging as the strongest performer and IREN showing the most room for improvement.**
"""